spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/book_store}
spring.datasource.username=${DB_USERNAME:postgres}
# XAMPP default has no password, so we keep password empty
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Email Configuration (Replace with your actual credentials)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nannapustaka.store@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
 
# Razorpay Configuration (Replace with your actual keys)
razorpay.key.id=rzp_test_Sm8cYrkGgyesFc
razorpay.key.secret=${RAZORPAY_SECRET}

# JWT Configuration
jwt.secret=${JWT_SECRET}
